//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISS_SportRecoveryGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BathSuggestionMap
    {
        public int SuggestionID { get; set; }
        public int ConditionID { get; set; }
        public int BathTypeID { get; set; }
        public bool IsRecommended { get; set; }
    
        public virtual BathCondition BathCondition { get; set; }
        public virtual BathType BathType { get; set; }
    }
}
