//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISS_SportRecoveryGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BathType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BathType()
        {
            this.BathSuggestionMap = new HashSet<BathSuggestionMap>();
            this.BathUsageGuideline = new HashSet<BathUsageGuideline>();
        }
    
        public int BathTypeID { get; set; }
        public string BathTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BathSuggestionMap> BathSuggestionMap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BathUsageGuideline> BathUsageGuideline { get; set; }
    }
}
