//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISS_SportRecoveryGuide.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TISS_SportRecoveryGuideDBEntities : DbContext
    {
        public TISS_SportRecoveryGuideDBEntities()
            : base("name=TISS_SportRecoveryGuideDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BathCondition> BathCondition { get; set; }
        public virtual DbSet<BathSuggestionMap> BathSuggestionMap { get; set; }
        public virtual DbSet<BathType> BathType { get; set; }
        public virtual DbSet<BathUsageGuideline> BathUsageGuideline { get; set; }
        public virtual DbSet<LogRecord> LogRecord { get; set; }
        public virtual DbSet<UserFeedback> UserFeedback { get; set; }
        public virtual DbSet<UserRawData> UserRawData { get; set; }
        public virtual DbSet<UserReferenceRecord> UserReferenceRecord { get; set; }
    }
}
