//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TISS_SportRecoveryGuide.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserReferenceRecord
    {
        public int ID { get; set; }
        public string Gender { get; set; }
        public Nullable<int> UserAge { get; set; }
        public string TeamName { get; set; }
        public string UsagePurpose { get; set; }
        public string UsedType { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public Nullable<bool> IsHelpful { get; set; }
        public string Feedback { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
    }
}
